import { AssetCategory } from './models';

/**
 * Global allowed assets list
 * This controls which assets will be tracked across all providers
 */


export interface AllowedAsset {
    name: string;
    displayName: string | null;
    tv_sym: string | null;
}


export const ALLOWED_ASSETS: Record<AssetCategory, AllowedAsset[]> = {

    crypto: [
        { name: "FILUSD", displayName: "FIL / USD", tv_sym: "COINBASE:FILUSD" },
        { name: "ETHUSD", displayName: "ETH / USD", tv_sym: "COINBASE:ETHUSD" },
        { name: "DOTUSD", displayName: "DOT / USD", tv_sym: "COINBASE:DOTUSD" },
        { name: "WBTCUSD", displayName: "WBTC / USD", tv_sym: "BINANCE:WBTCUSD" },
        { name: "VETUSD", displayName: "VET / USD", tv_sym: "COINBASE:VETUSD" },
        { name: "AXSUSD", displayName: "AXS / USD", tv_sym: "coinbase:AXSUSD" },
        { name: "AAVEUSD", displayName: "AAVE / USD", tv_sym: "coinbase:AAVEUSD" },
        { name: "TRXUSD", displayName: "TRX / USD", tv_sym: "KRAKEN:TRXUSD" },
        { name: "BNBUSD", displayName: "BNB / USD", tv_sym: "BINANCEUS:BNBUSD" },
        { name: "NEOUSD", displayName: "NEO / USD", tv_sym: "BITFINEX:NEOUSD" },
        { name: "DOGEUSD", displayName: "DOGE / USD", tv_sym: "COINBASE:DOGEUSD" },
        { name: "KSMUSD", displayName: "KSM / USD", tv_sym: "COINBASE:KSMUSD" },
        { name: "XTZUSD", displayName: "XTZ / USD", tv_sym: "COINBASE:XTZUSD" },
        { name: "USDTUSD", displayName: "USDT / USD", tv_sym: "COINBASE:USDTUSD" },
        { name: "XRPUSD", displayName: "XRP / USD", tv_sym: "BITSTAMP:XRPUSD" },
        { name: "ATOMUSD", displayName: "ATOM / USD", tv_sym: "KRAKEN:ATOMUSD" },
        { name: "CROUSD", displayName: "CRO / USD", tv_sym: "coinbase:CROUSD" },
        { name: "AVAXUSD", displayName: "AVAX / USD", tv_sym: "BITSTAMP:AVAXUSD" },
        { name: "CAKEUSD", displayName: "CAKE / USD", tv_sym: "BINANCE:CAKEUSD" },
        { name: "USDCUSD", displayName: "USDC / USD", tv_sym: "BITSTAMP:USDCUSD" },
        { name: "ADAUSD", displayName: "ADA / USD", tv_sym: "KRAKEN:ADAUSD" },
        { name: "UNIUSD", displayName: "UNI / USD", tv_sym: "KRAKEN:UNIUSD" },
        { name: "EOSUSD", displayName: "EOS / USD", tv_sym: "KRAKEN:EOSUSD" },
        { name: "ICPUSD", displayName: "ICP / USD", tv_sym: "COINBASE:ICPUSD" },
        { name: "GRTUSD", displayName: "GRT / USD", tv_sym: "COINBASE:GRTUSD" },
        { name: "THETAUSD", displayName: "THETA / USD", tv_sym: "BINANCE:THETAUSD" },
        { name: "SOLUSD", displayName: "SOL / USD", tv_sym: "BINANCE:SOLUSD" },
        { name: "XLMUSD", displayName: "XLM / USD", tv_sym: "COINBASE:XLMUSD" },
        { name: "ALGOUSD", displayName: "ALGO / USD", tv_sym: "KRAKEN:ALGOUSD" },
        { name: "BCHUSD", displayName: "BCH / USD", tv_sym: "BITSTAMP:BCHUSD" },
        { name: "MKRUSD", displayName: "MKR / USD", tv_sym: "coinbase:MKRUSD" },
        { name: "DASHUSD", displayName: "DASH / USD", tv_sym: "KRAKEN:DASHUSD" },
        { name: "BTCUSD", displayName: "BTC / USD", tv_sym: "BITSTAMP:BTCUSD" },
        { name: "LINKUSD", displayName: "LINK / USD", tv_sym: "BITSTAMP:LINKUSD" },
        { name: "LTCUSD", displayName: "LTC / USD", tv_sym: "COINBASE:LTCUSD" },
    ],

    stocks: [
        { name: "SCGLY", displayName: "Société Générale SA", tv_sym: "OTC:SCGLY" },
        { name: "T", displayName: "AT&T Inc.", tv_sym: "NYSE:T" },
        { name: "MCO", displayName: "Moody's Corporation", tv_sym: "NYSE:MCO" },
        { name: "WIX", displayName: "Wix.com Ltd.", tv_sym: "NASDAQ:WIX" },
        { name: "VWAGY", displayName: "Volkswagen AG", tv_sym: "OTC:VWAGY" },
        { name: "AAP", displayName: "Advance Auto Parts, Inc.", tv_sym: "NYSE:AAP" },
        { name: "GM", displayName: "General Motors Company", tv_sym: "NYSE:GM" },
        { name: "MRK", displayName: "Merck & Co., Inc.", tv_sym: "NYSE:MRK" },
        { name: "ADDYY", displayName: "adidas AG", tv_sym: "OTC:ADDYY" },
        { name: "TEVA", displayName: "Teva Pharmaceutical Industries Limited", tv_sym: "NYSE:TEVA" },
        { name: "TSM", displayName: "Taiwan Semiconductor Manufacturing Company Limited", tv_sym: "NYSE:TSM" },
        { name: "MCD", displayName: "McDonald's Corporation", tv_sym: "NYSE:MCD" },
        { name: "DIS", displayName: "The Walt Disney Company", tv_sym: "NYSE:DIS" },
        { name: "MGM", displayName: "MGM Resorts International", tv_sym: "NYSE:MGM" },
        { name: "DELL", displayName: "Dell Technologies Inc.", tv_sym: "NYSE:DELL" },
        { name: "KHC", displayName: "The Kraft Heinz Company", tv_sym: "NASDAQ:KHC" },
        { name: "DANOY", displayName: "Danone S.A.", tv_sym: "OTC:DANOY" },
        { name: "BBVA", displayName: "Banco Bilbao Vizcaya Argentaria, S.A.", tv_sym: "NYSE:BBVA" },
        { name: "ACN", displayName: "Accenture plc", tv_sym: "NYSE:ACN" },
        { name: "PYPL", displayName: "PayPal Holdings, Inc.", tv_sym: "NASDAQ:PYPL" },
        { name: "TMO", displayName: "Thermo Fisher Scientific Inc.", tv_sym: "NYSE:TMO" },
        { name: "BK", displayName: "The Bank of New York Mellon Corporation", tv_sym: "NYSE:BK" },
        { name: "GILD", displayName: "Gilead Sciences, Inc.", tv_sym: "NASDAQ:GILD" },
        { name: "BABA", displayName: "Alibaba Group Holding Limited", tv_sym: "NYSE:BABA" },
        { name: "MRNA", displayName: "Moderna, Inc.", tv_sym: "NASDAQ:MRNA" },
        { name: "AMAT", displayName: "Applied Materials, Inc.", tv_sym: "NASDAQ:AMAT" },
        { name: "BA", displayName: "The Boeing Company", tv_sym: "NYSE:BA" },
        { name: "HSBC", displayName: "HSBC Holdings plc", tv_sym: "NYSE:HSBC" },
        { name: "TMC", displayName: "TMC the metals company Inc.", tv_sym: "NASDAQ:TMC" },
        { name: "AVGO", displayName: "Broadcom Inc.", tv_sym: "NASDAQ:AVGO" },
        { name: "DAL", displayName: "Delta Air Lines, Inc.", tv_sym: "NYSE:DAL" },
        { name: "INTC", displayName: "Intel Corporation", tv_sym: "NASDAQ:INTC" },
        { name: "TXN", displayName: "Texas Instruments Incorporated", tv_sym: "NASDAQ:TXN" },
        { name: "AZO", displayName: "AutoZone, Inc.", tv_sym: "NYSE:AZO" },
        { name: "AAPL", displayName: "Apple Inc.", tv_sym: "NASDAQ:AAPL" },
        { name: "AIG", displayName: "American International Group, Inc.", tv_sym: "NYSE:AIG" },
        { name: "JNJ", displayName: "Johnson & Johnson", tv_sym: "NYSE:JNJ" },
        { name: "NIO", displayName: "NIO Inc.", tv_sym: "NYSE:NIO" },
        { name: "AMZN", displayName: "Amazon.com, Inc.", tv_sym: "NASDAQ:AMZN" },
        { name: "GOOG", displayName: "Alphabet Inc.", tv_sym: "NASDAQ:GOOG" },
        { name: "CGC", displayName: "Canopy Growth Corporation", tv_sym: "NASDAQ:CGC" },
        { name: "TWTR", displayName: "Twitter, Inc. (delisted)", tv_sym: "NYSE:TWTR" },
        { name: "PFE", displayName: "Pfizer Inc.", tv_sym: "NYSE:PFE" },
        { name: "EBAY", displayName: "eBay Inc.", tv_sym: "NASDAQ:EBAY" },
        { name: "NVDA", displayName: "NVIDIA Corporation", tv_sym: "NASDAQ:NVDA" },
        { name: "SAN", displayName: "Banco Santander, S.A.", tv_sym: "NYSE:SAN" },
        { name: "BNPQF", displayName: "BNP Paribas SA", tv_sym: "OTC:BNPQF" },
        { name: "UBER", displayName: "Uber Technologies, Inc.", tv_sym: "NYSE:UBER" },
        { name: "TRIP", displayName: "Tripadvisor, Inc.", tv_sym: "NASDAQ:TRIP" },
        { name: "RACE", displayName: "Ferrari N.V.", tv_sym: "NYSE:RACE" },
        { name: "CMCSA", displayName: "Comcast Corporation", tv_sym: "NASDAQ:CMCSA" },
        { name: "TSLA", displayName: "Tesla, Inc.", tv_sym: "NASDAQ:TSLA" },
        { name: "SHOP", displayName: "Shopify Inc.", tv_sym: "NASDAQ:SHOP" },
        { name: "BMY", displayName: "Bristol-Myers Squibb Company", tv_sym: "NYSE:BMY" },
        { name: "MA", displayName: "Mastercard Incorporated", tv_sym: "NYSE:MA" },
        { name: "NKE", displayName: "NIKE, Inc.", tv_sym: "NYSE:NKE" },
        { name: "LVMHF", displayName: "LVMH Moët Hennessy - Louis Vuitton, Société Européenne", tv_sym: "OTC:LVMHF" },
        { name: "NFLX", displayName: "Netflix, Inc.", tv_sym: "NASDAQ:NFLX" },
        { name: "CSCO", displayName: "Cisco Systems, Inc.", tv_sym: "NASDAQ:CSCO" },
        { name: "BCS", displayName: "Barclays PLC", tv_sym: "NYSE:BCS" },
        { name: "MMM", displayName: "3M Company", tv_sym: "NYSE:MMM" },
        { name: "SIEGY", displayName: "Siemens AG", tv_sym: "OTC:SIEGY" },
        { name: "F", displayName: "Ford Motor Company", tv_sym: "NYSE:F" },
        { name: "VZ", displayName: "Verizon Communications Inc.", tv_sym: "NYSE:VZ" },
        { name: "ADI", displayName: "Analog Devices, Inc.", tv_sym: "NASDAQ:ADI" },
        { name: "XOM", displayName: "Exxon Mobil Corporation", tv_sym: "NYSE:XOM" },
        { name: "NRG", displayName: "NRG Energy, Inc.", tv_sym: "NYSE:NRG" },
        { name: "BAC", displayName: "Bank of America Corporation", tv_sym: "NYSE:BAC" },
        { name: "IBM", displayName: "International Business Machines Corporation", tv_sym: "NYSE:IBM" },
        { name: "NEE", displayName: "NextEra Energy, Inc.", tv_sym: "NYSE:NEE" },
        { name: "AFL", displayName: "Aflac Incorporated", tv_sym: "NYSE:AFL" },
        { name: "GS", displayName: "The Goldman Sachs Group, Inc.", tv_sym: "NYSE:GS" },
        { name: "SBUX", displayName: "Starbucks Corporation", tv_sym: "NASDAQ:SBUX" },
        { name: "MSFT", displayName: "Microsoft Corporation", tv_sym: "NASDAQ:MSFT" },
        { name: "QCOM", displayName: "QUALCOMM Incorporated", tv_sym: "NASDAQ:QCOM" },
        { name: "C", displayName: "Citigroup Inc.", tv_sym: "NYSE:C" },
        { name: "BIDU", displayName: "Baidu, Inc.", tv_sym: "NASDAQ:BIDU" },
        { name: "ADBE", displayName: "Adobe Inc.", tv_sym: "NASDAQ:ADBE" },
        { name: "JPM", displayName: "JPMorgan Chase & Co.", tv_sym: "NYSE:JPM" },
        { name: "WFC", displayName: "Wells Fargo & Company", tv_sym: "NYSE:WFC" },
        { name: "V", displayName: "Visa Inc.", tv_sym: "NYSE:V" },
        { name: "ORCL", displayName: "Oracle Corporation", tv_sym: "NYSE:ORCL" },
        { name: "PG", displayName: "The Procter & Gamble Company", tv_sym: "NYSE:PG" },
        { name: "ALK", displayName: "Alaska Air Group, Inc.", tv_sym: "NYSE:ALK" },
        { name: "ZM", displayName: "Zoom Video Communications, Inc.", tv_sym: "NASDAQ:ZM" },
        { name: "CRON", displayName: "Cronos Group Inc.", tv_sym: "NASDAQ:CRON" },
        { name: "CVX", displayName: "Chevron Corporation", tv_sym: "NYSE:CVX" },
    ],

    forex: [
        { name: "EURUSD", displayName: "EUR/USD", tv_sym: "FX_IDC:EURUSD" },
        { name: "GBPUSD", displayName: "GBP/USD", tv_sym: "FX_IDC:GBPUSD" },
        { name: "GBPCHF", displayName: "GBP/CHF", tv_sym: "FX_IDC:GBPCHF" },
        { name: "EURNOK", displayName: "EUR/NOK", tv_sym: "FX_IDC:EURNOK" },
        { name: "AUDJPY", displayName: "AUD/JPY", tv_sym: "FX_IDC:AUDJPY" },
        { name: "NZDCAD", displayName: "NZD/CAD", tv_sym: "FX:NZDCAD" },
        { name: "EURPLN", displayName: "EUR/PLN", tv_sym: "FX:EURPLN" },
        { name: "USDHKD", displayName: "USD/HKD", tv_sym: "FX:USDHKD" },
        { name: "USDCHF", displayName: "USD/CHF", tv_sym: "FX:USDCHF" },
        { name: "SGDJPY", displayName: "SGD/JPY", tv_sym: "FX:SGDJPY" },
        { name: "CADCHF", displayName: "CAD/CHF", tv_sym: "FX:CADCHF" },
        { name: "USDSGD", displayName: "USD/SGD", tv_sym: "FX:USDSGD" },
        { name: "CADJPY", displayName: "CAD/JPY", tv_sym: "FX:CADJPY" },
        { name: "USDTRY", displayName: "USD/TRY", tv_sym: "FX:USDTRY" },
        { name: "EURHUF", displayName: "EUR/HUF", tv_sym: "FX:EURHUF" },
        { name: "USDSEK", displayName: "USD/SEK", tv_sym: "FX:USDSEK" },
        { name: "AUDCHF", displayName: "AUD/CHF", tv_sym: "FX:AUDCHF" },
        { name: "AUDCAD", displayName: "AUD/CAD", tv_sym: "FX:AUDCAD" },
        { name: "EURCHF", displayName: "EUR/CHF", tv_sym: "FX:EURCHF" },
        { name: "USDCNH", displayName: "USD/CNH", tv_sym: "FX:USDCNH" },
        { name: "USDPLN", displayName: "USD/PLN", tv_sym: "FX:USDPLN" },
        { name: "USDJPY", displayName: "USD/JPY", tv_sym: "FX:USDJPY" },
        { name: "GBPJPY", displayName: "GBP/JPY", tv_sym: "FX:GBPJPY" },
        { name: "USDHUF", displayName: "USD/HUF", tv_sym: "FX:USDHUF" },
        { name: "GBPCAD", displayName: "GBP/CAD", tv_sym: "FX:GBPCAD" },
        { name: "EURSEK", displayName: "EUR/SEK", tv_sym: "FX:EURSEK" },
        { name: "USDMXN", displayName: "USD/MXN", tv_sym: "FX:USDMXN" },
        { name: "USDNOK", displayName: "USD/NOK", tv_sym: "FX:USDNOK" },
        { name: "ZARJPY", displayName: "ZAR/JPY", tv_sym: "FX:ZARJPY" },
        { name: "EURCAD", displayName: "EUR/CAD", tv_sym: "FX:EURCAD" },
        { name: "USDZAR", displayName: "USD/ZAR", tv_sym: "FX:USDZAR" },
        { name: "CHFJPY", displayName: "CHF/JPY", tv_sym: "FX:CHFJPY" },
        { name: "NZDJPY", displayName: "NZD/JPY", tv_sym: "FX:NZDJPY" },
        { name: "USDDKK", displayName: "USD/DKK", tv_sym: "FX:USDDKK" },
        { name: "USDCAD", displayName: "USD/CAD", tv_sym: "FX:USDCAD" },
        { name: "NZDCHF", displayName: "NZD/CHF", tv_sym: "FX:NZDCHF" },
        { name: "EURTRY", displayName: "EUR/TRY", tv_sym: "FX:EURTRY" },
        { name: "EURJPY", displayName: "EUR/JPY", tv_sym: "FX:EURJPY" },
    ],

    indices: [
        { name: "US30_USD", displayName: "US Wall St 30", tv_sym: "OANDA:US30USD" },
        { name: "JP225Y_JPY", displayName: "Japan 225 (JPY)", tv_sym: "OANDA:JP225YJPY" },
        { name: "CN50_USD", displayName: "China A50", tv_sym: "OANDA:CN50USD" },
        { name: "CH20_CHF", displayName: "Switzerland 20", tv_sym: "OANDA:CH20CHF" },
        { name: "ESPIX_EUR", displayName: "Spain 35", tv_sym: "OANDA:ESPIXEUR" },
        { name: "SPX500_USD", displayName: "US SPX 500", tv_sym: "OANDA:SPX500USD" },
        { name: "EU50_EUR", displayName: "Europe 50", tv_sym: "OANDA:EU50EUR" },
        { name: "HK33_HKD", displayName: "Hong Kong 33", tv_sym: "OANDA:HK33HKD" },
        { name: "US2000_USD", displayName: "US Russ 2000", tv_sym: "OANDA:US2000USD" },
        { name: "NAS100_USD", displayName: "US Nas 100", tv_sym: "OANDA:NAS100USD" },
        { name: "DE30_EUR", displayName: "Germany 30", tv_sym: "OANDA:DE30EUR" },
        { name: "NL25_EUR", displayName: "Netherlands 25", tv_sym: "OANDA:NL25EUR" },
        { name: "CHINAH_HKD", displayName: "China H Shares", tv_sym: "OANDA:CHINAHHKD" },
        { name: "SG30_SGD", displayName: "Singapore 30", tv_sym: "OANDA:SG30SGD" },
        { name: "AU200_AUD", displayName: "Australia 200", tv_sym: "OANDA:AU200AUD" },
        { name: "JP225_USD", displayName: "Japan 225", tv_sym: "OANDA:JP225USD" },
        { name: "FR40_EUR", displayName: "France 40", tv_sym: "OANDA:FR40EUR" },
        { name: "UK100_GBP", displayName: "UK 100", tv_sym: "OANDA:UK100GBP" },
    ],
    commodities: [
        { name: "XAU_USD", displayName: "Gold", tv_sym: "OANDA:XAUUSD" },
        { name: "XAU_NZD", displayName: "Gold/NZD", tv_sym: "OANDA:XAUNZD" },
        { name: "XAG_CHF", displayName: "Silver/CHF", tv_sym: "OANDA:XAGCHF" },
        { name: "XAG_HKD", displayName: "Silver/HKD", tv_sym: "OANDA:XAGHKD" },
        { name: "XAU_JPY", displayName: "Gold/JPY", tv_sym: "OANDA:XAUJPY" },
        { name: "XAU_HKD", displayName: "Gold/HKD", tv_sym: "OANDA:XAUHKD" },
        { name: "XAG_AUD", displayName: "Silver/AUD", tv_sym: "OANDA:XAGAUD" },
        { name: "WTICO_USD", displayName: "West Texas Oil", tv_sym: "OANDA:WTICOUSD" },
        { name: "XAG_NZD", displayName: "Silver/NZD", tv_sym: "OANDA:XAGNZD" },
        { name: "XAG_JPY", displayName: "Silver/JPY", tv_sym: "OANDA:XAGJPY" },
        { name: "XAG_GBP", displayName: "Silver/GBP", tv_sym: "OANDA:XAGGBP" },
        { name: "BCO_USD", displayName: "Brent Crude Oil", tv_sym: "OANDA:BCOUSD" },
        { name: "XAU_SGD", displayName: "Gold/SGD", tv_sym: "OANDA:XAUSGD" },
        { name: "XAU_XAG", displayName: "Gold/Silver", tv_sym: "OANDA:XAUXAG" },
        { name: "XCU_USD", displayName: "Copper", tv_sym: "OANDA:XCUUSD" },
        { name: "XAG_EUR", displayName: "Silver/EUR", tv_sym: "OANDA:XAGEUR" },
        { name: "XAU_GBP", displayName: "Gold/GBP", tv_sym: "OANDA:XAUGBP" },
        { name: "NATGAS_USD", displayName: "Natural Gas", tv_sym: "OANDA:NATGASUSD" },
        { name: "XPT_USD", displayName: "Platinum", tv_sym: "OANDA:XPTUSD" },
        { name: "CORN_USD", displayName: "Corn", tv_sym: "OANDA:CORNUSD" },
        { name: "XAU_EUR", displayName: "Gold/EUR", tv_sym: "OANDA:XAUEUR" },
        { name: "SOYBN_USD", displayName: "Soybeans", tv_sym: "OANDA:SOYBNUSD" },
        { name: "XAG_SGD", displayName: "Silver/SGD", tv_sym: "OANDA:XAGSGD" },
        { name: "XAG_CAD", displayName: "Silver/CAD", tv_sym: "OANDA:XAGCAD" },
        { name: "XAU_AUD", displayName: "Gold/AUD", tv_sym: "OANDA:XAUAUD" },
        { name: "WHEAT_USD", displayName: "Wheat", tv_sym: "OANDA:WHEATUSD" },
        { name: "XAU_CHF", displayName: "Gold/CHF", tv_sym: "OANDA:XAUCHF" },
        { name: "XAG_USD", displayName: "Silver", tv_sym: "OANDA:XAGUSD" },
        { name: "SUGAR_USD", displayName: "Sugar", tv_sym: "OANDA:SUGARUSD" },
        { name: "XPD_USD", displayName: "Palladium", tv_sym: "OANDA:XPDUSD" },
        { name: "XAU_CAD", displayName: "Gold/CAD", tv_sym: "OANDA:XAUCAD" },
    ],
    metals: [
        { name: "XAU_USD", displayName: "Gold", tv_sym: "OANDA:XAUUSD" },
        { name: "XAU_NZD", displayName: "Gold/NZD", tv_sym: "OANDA:XAUNZD" },
        { name: "XAG_CHF", displayName: "Silver/CHF", tv_sym: "OANDA:XAGCHF" },
        { name: "XAG_HKD", displayName: "Silver/HKD", tv_sym: "OANDA:XAGHKD" },
        { name: "XAU_JPY", displayName: "Gold/JPY", tv_sym: "OANDA:XAUJPY" },
        { name: "XAU_HKD", displayName: "Gold/HKD", tv_sym: "OANDA:XAUHKD" },
        { name: "XAG_AUD", displayName: "Silver/AUD", tv_sym: "OANDA:XAGAUD" },
        { name: "XAG_NZD", displayName: "Silver/NZD", tv_sym: "OANDA:XAGNZD" },
        { name: "XAG_JPY", displayName: "Silver/JPY", tv_sym: "OANDA:XAGJPY" },
        { name: "XAG_GBP", displayName: "Silver/GBP", tv_sym: "OANDA:XAGGBP" },
        { name: "XAU_SGD", displayName: "Gold/SGD", tv_sym: "OANDA:XAUSGD" },
        { name: "XAU_XAG", displayName: "Gold/Silver", tv_sym: "OANDA:XAUXAG" },
        { name: "XCU_USD", displayName: "Copper", tv_sym: "OANDA:XCUUSD" },
        { name: "XAG_EUR", displayName: "Silver/EUR", tv_sym: "OANDA:XAGEUR" },
        { name: "XAU_GBP", displayName: "Gold/GBP", tv_sym: "OANDA:XAUGBP" },
        { name: "XPT_USD", displayName: "Platinum", tv_sym: "OANDA:XPTUSD" },
        { name: "XAU_EUR", displayName: "Gold/EUR", tv_sym: "OANDA:XAUEUR" },
        { name: "XAG_SGD", displayName: "Silver/SGD", tv_sym: "OANDA:XAGSGD" },
        { name: "XAG_CAD", displayName: "Silver/CAD", tv_sym: "OANDA:XAGCAD" },
        { name: "XAU_AUD", displayName: "Gold/AUD", tv_sym: "OANDA:XAUAUD" },
        { name: "XAU_CHF", displayName: "Gold/CHF", tv_sym: "OANDA:XAUCHF" },
        { name: "XAG_USD", displayName: "Silver", tv_sym: "OANDA:XAGUSD" },
        { name: "XPD_USD", displayName: "Palladium", tv_sym: "OANDA:XPDUSD" },
        { name: "XAU_CAD", displayName: "Gold/CAD", tv_sym: "OANDA:XAUCAD" },
    ]
};


export function getAllAllowedAssets(): string[] {
    return Object.values(ALLOWED_ASSETS).flatMap(category =>
        category.map(asset => asset.name)
    );
}

export function getAssetDisplayName(assetName: string): string {
    for (const category of Object.values(ALLOWED_ASSETS)) {
        const asset = category.find(a => a.name === assetName);
        if (asset) {
            return asset.displayName || assetName;
        }
    }
    return assetName;
}


export function getAssetTradingViewSymbol(assetName: string): string | null {
    for (const category of Object.values(ALLOWED_ASSETS)) {
        const asset = category.find(a => a.name === assetName);
        if (asset) {
            return asset.tv_sym;
        }
    }
    return null;
}
